### ISSUE TITLE
github icon 不可点击

### ISSUE THREAD

**Issue by AnonBug** [liujuntao123/chines-history-video#2]
兄弟，你的 icon 点击穿透有问题，只有按钮边缘区域可点击
<img width="71" alt="image" src="https://github.com/liujuntao123/chines-history-video/assets/47171062/17004425-30d7-45b3-b93c-15b18ef7293e">

**Comment by liujuntao123** [comment]
> 兄弟，你的 icon 点击穿透有问题，只有按钮边缘区域可点击 <img alt="image" width="71" src="https://private-user-images.githubusercontent.com/47171062/294364995-17004425-30d7-45b3-b93c-15b18ef7293e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDEyMzQsIm5iZiI6MTcwNDcwMDkzNCwicGF0aCI6Ii80NzE3MTA2Mi8yOTQzNjQ5OTUtMTcwMDQ0MjUtMzBkNy00NWIzLWI5M2MtMTViMThlZjcyOTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA4MDIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiYTY4MDBhYTc1ZjJhNTg1YjA3ODhkMWYzYTFkNTIxNjkwODg0ZGIwMTNkNzEwMmI2ZTMyOGQ2ZGQ1MjkyZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5G3c3QwI4BWI_RhntBW3zsEcvmC6NQ258Xsxh01-Nhw">

我验证了一下，不能复现此问题，这个icon包裹的是a标签，理论上不会有点击穿透的问题。如还有问题，欢迎提供进一步的复现场景。
