### ISSUE TITLE
【UP收录提名】清朝史 - 提名 正直讲史-李正Str

### ISSUE THREAD

**Issue by Johnwjl** [liujuntao123/chines-history-video#3]
非常喜欢你的网站，我已经把你的网站分享到了各个历史UP的评论区，希望分享给更多喜欢历史的人。

我提名一个自己一直关注的UP，正直讲史-李正Str  https://space.bilibili.com/11646119/channel/series  ，他主要讲的是清朝的历史。

我看到目前每个朝代里只嵌入了一个UP的B站视频，后续期待你可以在每个朝代里加入更多优质UP的视频。

**Comment by liujuntao123** [comment]
感谢推荐，已加入
